../bench_c++_mt_nomutex_sleep/linuxscript_batch.sh
sleep(120)
../bench_c++_mt_nomutex_forker/linuxscript.sh
sleep(120)
../bench_c++_mt_nomutex/nomutexscript.sh
sleep(120)
../bench_c++_mt_v2/ver2script.sh
sleep(120)
../bench_c++_multithreaded/scripter.sh
sleep(120)